#!/bin/bash

# GitUp Make Repository

git init
git add .
echo "Commit message (without quotes):"
read commitm
git commit -m "$commitm"
echo "Your username:"
read $username
echo "Repository name:"
read $reponame
git remote add origin https://github.com/"$username"/"$reponame".git
git push -u origin master
