#!/bin/bash

# GitUp script
# Federico Damián Schonborn (feskyde)
# 2015

echo "Adding files..."
git add .
echo ""
echo "Write your commit message here (without quotes):"
read commitm
echo ""
echo "Adding message to commit..."
git commit -m "$commitm"
echo ""
echo "Pushing to master branch..."
git push -u origin master
echo ""
